services:
  db:
    image: postgres:18-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ecom_production
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ecom_production"]
      interval: 5s
      timeout: 5s
      retries: 5

  elasticsearch:
    image: elasticsearch:9.3.3
    container_name: shared_elasticsearch
    restart: unless-stopped
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    networks:
      - default
      - shared_elastic_net

  web:
    image: smakthe/e-commerce:latest
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - RAILS_ENV=production
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@db:5432/ecom_production
      - ELASTICSEARCH_HOST=elasticsearch
    depends_on:
      db:
        condition: service_healthy
      elasticsearch:
        condition: service_started
    networks:
      - default
      - shared_elastic_net

volumes:
  postgres_data:
  elastic_data:

networks:
  shared_elastic_net:
    external: true